
* S1
- Subir slides a https://github.com/mpvdes/
- repasar github pages
- navegador como renderizador
- github: md a html. Diferente si usa jekyll
- HTTP como API, métodos.
- index.html? es obligatorio, pero hay configuraciones del servidor que pueden cambiar el comportamiento
- Arrancar servidor python -m http.server
- nano set autoindent, linenumber, tabular spaces,

* S2
- cita, mostrar enlace
- arrancar servidor y abrir
- mandar práctica de marcado de texto
- 

* texto para hacer marcado
TikTok se disculpa por el uso indebido de datos de menores de edad

La plataforma anuncia medidas para garantizar la protección de datos de los menores

TikTok, la popular plataforma de videos cortos, se ha disculpado por
el uso indebido de datos de menores de edad. Según un informe
publicado por la Comisión de Protección de Datos, la compañía recopiló
información de menores de edad sin el consentimiento de sus padres o
tutores legales. En un comunicado que ha realizado hoy TikTok ha
aceptado su responsabilidad y ha anunciado medidas para mejorar su
proceso de verificación de edad y para garantizar que se cumplan las
normas de protección de datos para menores de edad.

"Estamos muy preocupados por la privacidad de nuestros hijos, no
sabíamos que TikTok estaba recopilando información de ellos sin
nuestro consentimiento" declara la madre de un menor afectado por este
caso, "esperamos que TikTok tome medidas reales para garantizar que
esto no vuelva a suceder en el futuro".
  
Esta plataforma social en la que los usuarios pueden crear y
compartir videos cortos fue lanzada en 2016 por la empresa china
ByteDance y se ha vuelto muy popular en todo el mundo. Los usuarios
pueden grabar y editar videos con música, efectos y filtros, y
compartirlos en la plataforma. TikTok también tiene un algoritmo de
recomendación que sugiere videos a los usuarios basados en su
actividad en la plataforma. Además de compartir videos creados por sí
mismos, los usuarios también pueden seguir a otros usuarios y ver
videos que han compartido.

Según el medio de prensa digital TecnologiaHoy TikTok es una
plataforma peligrosa ya que recolecta y comparte información personal
de sus usuarios mediante el uso de cookies con entidades
gubernamentales y empresas privadas. Como hemos podido comprobar en
FactCheckTech.org TikTok se rige por las leyes de privacidad
establecidas en cada país en el que opera, y no tiene ninguna práctica
de compartir información personal de sus usuarios mediante cookies con
terceros sin su consentimiento.

Según la RAE, una cookie es un mecanismo utilizado por las páginas web
para mejorar la experiencia de navegación de los usuarios consistente
en crear en el ordenador del usuario un fichero informático con
información de sus preferencias, gustos y perfil, con el fin de que en
la próxima visita los contenidos y funcionalidades se ajusten a sus
preferencias.

La plataforma informa que la semana que viene implementará un sistema
de verificación de edad más robusto para asegurar que solo los
usuarios mayores de edad puedan crear cuentas y compartir información
en la plataforma. Además, TikTok está trabajando en una política de
privacidad más clara y detallada para informar a los usuarios sobre
cómo se recopila y utiliza su información personal.

TikTok también informa que se compromete a cumplir con las leyes y
regulaciones de protección de datos de cada país en el que opera, y
está trabajando en colaboración con las autoridades reguladoras para
garantizar que se cumplan estas normas.

La plataforma ha pedido disculpas a los usuarios afectados y ha
asegurado que está tomando medidas para evitar que situaciones
similares vuelvan a ocurrir en el futuro.

* texto en párrafos
  #+begin_src html
<p>TikTok se disculpa por el uso indebido de datos de menores de edad</p>
<p>La plataforma anuncia medidas para garantizar la protección de datos de los menores</p>
<p>TikTok, la popular plataforma de videos cortos, se ha disculpado por el uso indebido de datos de menores de edad. Según un informe publicado por la Comisión de Protección de Datos, la compañía recopiló información de menores de edad sin el consentimiento de sus padres o tutores legales. En un comunicado que ha realizado hoy TikTok ha aceptado su responsabilidad y ha anunciado medidas para mejorar su proceso de verificación de edad y para garantizar que se cumplan las normas de protección de datos para menores de edad.</p>
<p>"Estamos muy preocupados por la privacidad de nuestros hijos, no sabíamos que TikTok estaba recopilando información de ellos sin nuestro consentimiento" declara la madre de un menor afectado por este caso, "esperamos que TikTok tome medidas reales para garantizar que esto no vuelva a suceder en el futuro".</p>
<p>Esta plataforma social en la que los usuarios pueden crear y compartir videos cortos fue lanzada en 2016 por la empresa china ByteDance y se ha vuelto muy popular en todo el mundo. Los usuarios pueden grabar y editar videos con música, efectos y filtros, y compartirlos en la plataforma. TikTok también tiene un algoritmo de recomendación que sugiere videos a los usuarios basados en su actividad en la plataforma. Además de compartir videos creados por sí mismos, los usuarios también pueden seguir a otros usuarios y ver videos que han compartido.</p>
<p>Según el medio de prensa digital TecnologiaHoy TikTok es una plataforma peligrosa ya que recolecta y comparte información personal de sus usuarios mediante el uso de cookies con entidades gubernamentales y empresas privadas. Como hemos podido comprobar en FactCheckTech.org TikTok se rige por las leyes de privacidad establecidas en cada país en el que opera, y no tiene ninguna práctica de compartir información personal de sus usuarios mediante cookies con terceros sin su consentimiento.</p>
<p>Según la RAE, una cookie es un mecanismo utilizado por las páginas web para mejorar la experiencia de navegación de los usuarios consistente en crear en el ordenador del usuario un fichero informático con información de sus preferencias, gustos y perfil, con el fin de que en la próxima visita los contenidos y funcionalidades se ajusten a sus preferencias.</p>
<p>La plataforma informa que la semana que viene implementará un sistema de verificación de edad más robusto para asegurar que solo los usuarios mayores de edad puedan crear cuentas y compartir información en la plataforma. Además, TikTok está trabajando en una política de privacidad más clara y detallada para informar a los usuarios sobre cómo se recopila y utiliza su información personal.</p>
<p>En resumen, TikTok se disculpa por el uso indebido de datos de menores de edad y anuncia medidas para garantizar la protección de datos de los menores, incluyendo un sistema de verificación de edad más robusto, una política de privacidad más clara y detallada y cumplimiento con las leyes y regulaciones de protección de datos de cada país en el que opera.</p>
  #+end_src
* Martes
- Dudas Arantxa
- Columnas bootstrap
- HTML: video-front
- HTML: Tipografía
- HTML: formulario, input, button, radio, checkbox
- Crear developer account twitter
** Accesibilidad
   - img alt
   - contenido relacionado: main, article, section, header, footer, etc
   - audio
   - form
   - 
* Miércoles
- javascript; https://y.com.sb/watch?v=PkZNo7MFNFg
- scrollify
- 
* Bot
  - https://twitter.com/GranViaCerrada
  - https://twitter.com/manuelrico
  - https://www.youtube.com/watch?v=Rz886HkV1j4
  - https://mybot-team.github.io/documentacion/alojando-bot-en-glitch.html
  - https://scribe.citizen4.eu/shiro-discord-bot/how-to-host-any-node-js-bot-for-free-5cff927d3aa3
  - https://www.linode.com/docs/guides/nodejs-twitter-bot/
    - 
* Date
  - https://scribe.citizen4.eu/m/global-identity?redirectUrl=https%3A%2F%2Fblog.bitsrc.io%2Fhow-to-handle-time-zones-in-javascript-b135a7931453
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
  - 
* Timeline
  - El propio de LoveLace
  - El de whitney houston
* Soundcite
  - https://www.nytimes.com/interactive/2014/04/13/magazine/blues.html?mtrref=soundcite.knightlab.com&gwh=E87B8F243FC7A5DF8C9186763E53A3A7
  - http://projects.aljazeera.com/2014/tangier-island/
* Justapox
  - https://interaktiv.morgenpost.de/berlin-1945-2015/
  - 
* Accesibilidad
  - https://validator.w3.org/nu/
  - https://www.a11yproject.com/
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
  - https://developer.mozilla.org/en-US/docs/Learn/Accessibility
  - https://egghead.io/lessons/aria-accessible-button-events
  - https://cccaccessibility.org/resources/htctu/81/ 
  - https://www.youtube.com/watch?v=Vko5cC4SMSc
* Lazy-loading
  - https://caniuse.com/loading-lazy-attr
  - https://mathiasbynens.be/demo/img-loading-lazy
  - https://web.dev/browser-level-image-lazy-loading/#load-in-distance-threshold
  - https://httparchive.org/
  - 
* Web Performance
  - https://developer.mozilla.org/en-US/docs/Web/Performance
  - 
